### ISSUE TITLE
In mobile View Navbar Dropdown options color is not visible

### ISSUE THREAD

**Issue by srrathi** [SummerOfBitcoin/summer-of-bitcoin#1]
here is the screenshot of the exact bug.
![image](https://user-images.githubusercontent.com/57089237/121783858-bd9fcc80-cbce-11eb-9546-6ccc09ee4df8.png)

 In mobile view the navbar dropdown options font color is of similar color of that of background making them not visible unless a particular option is selected or we have opened that particular section.
 
 It's a very basic issue and as the website is made using bootstrap, So it wouldn't take much time to resolve it. I'll be more than happy to resolve it and help. Please do let me know.

**Comment by adi-shankara** [comment]
This is fixed.
